// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AnalyzeEndpoint(arg1:string):Promise<main.EndpointData>;

export function GetLiveMetrics():Promise<main.LiveMetrics>;

export function Greet(arg1:string):Promise<string>;

export function StartTrafficTest(arg1:string,arg2:string):Promise<void>;

export function StopTrafficTest():Promise<void>;
