// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AnalyzeEndpoint(arg1) {
  return window['go']['main']['App']['AnalyzeEndpoint'](arg1);
}

export function GetLiveMetrics() {
  return window['go']['main']['App']['GetLiveMetrics']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function StartTrafficTest(arg1, arg2) {
  return window['go']['main']['App']['StartTrafficTest'](arg1, arg2);
}

export function StopTrafficTest() {
  return window['go']['main']['App']['StopTrafficTest']();
}
